<?php
/**
 * Created by PhpStorm.
 * User: ThinkPad
 * Date: 2018/9/3
 * Time: 16:26
 */

namespace App\HttpController\Api;


use App\Utility\FormatResultErrors;

class Base extends AbstractBase
{
    protected $who;

    public function index()
    {
        parent::index(); // TODO: Change the autogenerated stub
    }

    public function onRequest($action): ?bool
    {
        $token = $this->request()->getRequestParam('token');

        if(empty($token)){
            $this->returnJson(FormatResultErrors::CODE_MAP['TOKEN.INVALID']);
            return false;
        }

        $user = \App\Model\User::authToken($token);
        if(!$user){
            $this->returnJson(FormatResultErrors::CODE_MAP['TOKEN.INVALID']);
            return false;
        }

        $this->who = $user;
        return true;
    }
}